CREATE TABLE fact_claims (
    claim_id VARCHAR(20) PRIMARY KEY,
    policy_id VARCHAR(20) NOT NULL,
    loss_date DATE NOT NULL,
    report_date DATE NOT NULL,
    assignment_date DATE,
    assessment_date DATE,
    decision_date DATE,
    settlement_date DATE,
    product_key INTEGER NOT NULL REFERENCES dim_product(product_key),
    region_key INTEGER NOT NULL REFERENCES dim_region(region_key),
    claim_type_key INTEGER NOT NULL REFERENCES dim_claim_type(claim_type_key),
    handler_key INTEGER NOT NULL REFERENCES dim_handler(handler_key),
    channel_key INTEGER NOT NULL REFERENCES dim_channel(channel_key),
    supplier_key INTEGER NOT NULL REFERENCES dim_supplier(supplier_key),
    status_key INTEGER NOT NULL REFERENCES dim_status(status_key),
    severity_key INTEGER NOT NULL REFERENCES dim_severity(severity_key),
    risk_key INTEGER NOT NULL REFERENCES dim_risk(risk_key),
    claim_amount DECIMAL(18,2) NOT NULL CHECK (claim_amount > 0),
    approved_amount DECIMAL(18,2) NOT NULL,
    paid_amount DECIMAL(18,2) NOT NULL,
    reserve_amount DECIMAL(18,2) NOT NULL,
    total_incurred DECIMAL(18,2) NOT NULL,
    fraud_risk_score DECIMAL(5,2) NOT NULL CHECK (fraud_risk_score BETWEEN 0 AND 100),
    fraud_referral_flag INTEGER NOT NULL CHECK (fraud_referral_flag IN (0,1)),
    synthetic_fraud_target_flag INTEGER NOT NULL CHECK (synthetic_fraud_target_flag IN (0,1)),
    reopened_flag INTEGER NOT NULL CHECK (reopened_flag IN (0,1)),
    complaint_flag INTEGER NOT NULL CHECK (complaint_flag IN (0,1)),
    sla_target_days INTEGER NOT NULL,
    settlement_days INTEGER,
    sla_met_flag INTEGER NOT NULL CHECK (sla_met_flag IN (0,1)),
    reporting_delay_days INTEGER NOT NULL,
    prior_claims_count INTEGER NOT NULL,
    policy_tenure_months INTEGER NOT NULL,
    claim_complexity VARCHAR(20) NOT NULL,
    open_claim_age_days INTEGER NOT NULL,
    ingestion_batch VARCHAR(7) NOT NULL,
    CHECK (report_date >= loss_date),
    CHECK (settlement_date IS NULL OR settlement_date >= report_date),
    CHECK (total_incurred = paid_amount + reserve_amount)
);

CREATE INDEX ix_fact_claims_loss_date ON fact_claims(loss_date);
CREATE INDEX ix_fact_claims_region_status ON fact_claims(region_key, status_key);
CREATE INDEX ix_fact_claims_risk ON fact_claims(fraud_risk_score);
